### ISSUE TITLE
Not clear no redeploy is needed on environment change

### ISSUE THREAD

**Issue by qnm** [bitgenics/linc#10]
**Is your feature request related to a problem? Please describe.**
If I change a key for my integration environment, I also want to re-deploy to ensure that key is in place.

**Describe the solution you'd like**
A mechanism to re-deploy when the environment changes

**Describe alternatives you've considered**
I can create a dummy commit and make it deploy but...

**Comment by evanderkoogh** [comment]
Hey @qnm. The settings are passed in at request time, so it shouldn't require a redeploy.
Is there a problem that you do not see the change reflected?
Or did you just expect there to be a redeploy needed and we need to make clear that isn't needed?

**Comment by qnm** [comment]
@evanderkoogh Ah - I assumed I needed to re-deploy. Thanks!

**Comment by evanderkoogh** [comment]
Thanks! I will work with @plexey to see what we can do to make it clearer that that isn't required.
