### ISSUE TITLE
Change URL for preview links associated to a site

### ISSUE THREAD

**Issue by Nibblesh** [bitgenics/linc#11]
**Is your feature request related to a problem? Please describe.**
I would like to rename a project's url after creation

**Describe the solution you'd like**
Allow site to be edited including slug

**Describe alternatives you've considered**
allow clone project and delete project where new project can copy environments and edit slug and name before creation

**Comment by evanderkoogh** [comment]
At least not yet. We can do this manually for you, contact the support email address for help.
