### ISSUE TITLE
gradient visual bug in Safari

### ISSUE THREAD

**Issue by mattdarveniza** [bitgenics/linc#12]
**Describe the bug**
The fade-out gradients in the build grid don't appear correctly in Safari

**To Reproduce**
1. Head to `https://app.linc.sh/sites/your-site-here` in Safari
2. Observe gradients on each build looking weird

**Expected behavior**
Text fades out on the right when it exceeds the length of the grid cell

**Screenshots**
<img width="2270" alt="Screen Shot 2019-06-17 at 10 51 52 am" src="https://user-images.githubusercontent.com/946261/59577052-5ea13d00-9105-11e9-9b69-8daa7fe3bfb7.png">

**Desktop:**
 - OS: macOS 10.14.4
 - Browser: Safari 
 - Version: 12.1

**Additional context**
Scrolling is really janky on this page in Safari too (but smooth as in Chrome), not sure if that's related to the gradient or something else.

**Comment by plexey** [comment]
Gradient bug should be fixed now in the latest release. @mattdarveniza can you confirm that it's working?

**Comment by mattdarveniza** [comment]
Yep looks good! Thanks.
