### ISSUE TITLE
Slack integration request

### ISSUE THREAD

**Issue by Nibblesh** [bitgenics/linc#13]
**Is your feature request related to a problem? Please describe.**
Team members without github access need to be sent linc preview links manually by developers.

**Describe the solution you'd like**
Ideal solution would be to be able to configure an integration with Slack, allowing builds that match a glob or multiple globs, to push a notification to a configured Slack channel.

**Comment by geelen** [comment]
Ooh I like the glob idea!

Got any thoughts about what kind of info you'd want for each new preview link? I'm thinking something like:

```
@username pushed commit "Commit message" on branch feat/x. Preview links available: production | staging.
```

Do you think that'll be enough context for your non-github peeps without being spammy?

**Comment by Nibblesh** [comment]
This seems reasonable!

My personal situation is that when we have visual changes percy.io sends a request link with branch and commit info. See image:

![image](https://user-images.githubusercontent.com/9124852/59730930-8d472100-9287-11e9-8129-43b6d6980d40.png)

so basically I want for the non github users to find the relevant linc preview link for the percy visual regression request

**Comment by plexey** [comment]
Alrighty, so been putting together some Linc slack integration:
![image](https://user-images.githubusercontent.com/19183324/60159997-c0fdea00-9837-11e9-9aee-6d97ba619a69.png)
We'll soon be extending the Linc UI to add a slack webhook url settings field, but for now I'll just PM you with setup instructions @Nibblesh.

**Comment by plexey** [comment]
Slack webhook URL configuration UI is now live:
![image](https://user-images.githubusercontent.com/19183324/60633246-1bf19b80-9e4d-11e9-8249-34c5d122364f.png)
We'll hopefully be extending this feature more over the next few weeks.
