### ISSUE TITLE
Preview links to specific environments on table view

### ISSUE THREAD

**Issue by Nibblesh** [bitgenics/linc#16]
**Is your feature request related to a problem? Please describe.**
I would like to click the preview link to a specific environment without having to go into the build results page

**Describe the solution you'd like**
Couple of different features which would make this more reasonable, but they would also work together

1) Allow per user or per org default preview environment. e.g. if selected as staging, then the preview links will launch against staging by default

2) Change the button to launch preview link in table view, to be a button group with two buttons
Left button will be the same as what it currently is, might be worth changing the contents from an icon to "open" or something.
Right button will open a drop down with a list of all environments so that you can click the environment you want to open that preview build against.

**Comment by evanderkoogh** [comment]
Hey @Nibblesh, this is good feedback. We will be having a look on how improve this use-case.

**Comment by plexey** [comment]
Hi @Nibblesh, we've just released a feature fulfilling the functionality you requested. 

Our solution differs slightly from the one you described insofar as we render a preview link for each environment per commit in place of the original single preview link icon:
![image](https://user-images.githubusercontent.com/19183324/60698589-6cdbbf80-9f33-11e9-8149-047b78e27cb1.png)

We wen't through a variety of designs and ended up liking this solution the most. I hope that this satisfies your use-case. Let us know how you get on :)
