### ISSUE TITLE
Master deployment has stalled

### ISSUE THREAD

**Issue by qnm** [bitgenics/linc#19]
It looks like #8 has resurfaced.

**Describe the bug**
After committing to the master branch (which was a squash commit), the Current Release has not updated nor been deployed.

**To Reproduce**

1. Accept a PR and commit to the master branch

**Expected behavior**
The master branch should be deployed. It was not.

**Screenshots**
<img width="990" alt="image" src="https://user-images.githubusercontent.com/5343/62095315-62f37500-b2c3-11e9-9148-7c6ce4775393.png">

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/5343/62095341-7bfc2600-b2c3-11e9-8114-6594bd1ee323.png">

**Comment by geelen** [comment]
Taking a look!

**Comment by geelen** [comment]
Ah, it looks like something you merged in (from dependabot) caused your commits on master to fail. Linc will only release commits to production with passing tests (preview links still get generated though). But we aren't passing that info through as a github status, so there was no red flag on that PR that would have prevented a merge.

Check https://app.linc.sh/sites/digivizer/commits/master and you should see the test failures. Click through to see the messages, seems like an AVA and Babel mismatch?

I'm closing this in favour of #20 which I'll get fixed ASAP
