### ISSUE TITLE
Windows scrollbars

### ISSUE THREAD

**Issue by Nibblesh** [bitgenics/linc#21]
**Describe the bug**
![image](https://user-images.githubusercontent.com/9124852/66356382-7b17fc80-e9b6-11e9-99e3-27564d824af6.png)

**To Reproduce**
1. Be on windows

**Expected behavior**
Be on MacOs

**Comment by evanderkoogh** [comment]
@plexey Didn't you look into this?

**Comment by plexey** [comment]
This issue should now be fixed on Edge browser.
Apologies for leaving this one to languish so long.
