### ISSUE TITLE
Failed to check out commit during build

### ISSUE THREAD

**Issue by wee007** [bitgenics/linc#22]
I have force pushed my changes to github and the linc build failed even after a rebuild with the following error:

```
Starting build...
git clone --depth=3 -b <xxx> https://x-access-token:<token>@github.com/<xxx>/<xxx> src
Cloning into 'src'...

0.62 sec
Failed: Failed to check out commit sha <xxx> on
```

**Comment by evanderkoogh** [comment]
Hey @wee007. That shouldn't happen. I'll take a look at it immediately.

**Comment by wee007** [comment]
Thanks @evanderkoogh !

**Comment by evanderkoogh** [comment]
Just send you an email at your personal (Github registered) account with some followup questions.

**Comment by wee007** [comment]
@evanderkoogh responded to your email.

**Comment by evanderkoogh** [comment]
For other people who run into this issue, it has to do with force pushing a rebase. The workaround is to just push a new commit on top of the other commit until we have fixed the issue.
