### ISSUE TITLE
Files under PUBLIC_URL should be exposed directly without redirect

### ISSUE THREAD

**Issue by qnm** [bitgenics/linc#26]
**Describe the bug**
We use the public directory as a place to store things that have to be referenced outside of the react app, such as images to be used in OpenGraph definitions, which are referenced from `public/index.html`.

I see that URLs which reference images in `/public` are redirecting to the compiled location.

e.g.

```
qnm@euans-mba ~> curl -I https://app.digivizer.com/platform.jpg
HTTP/2 302
content-length: 0
location: https://app.digivizer.com/_assets/_public/platform.d59298f38.jpg
```

OpenGraph consumers don't always resolve the redirects, which results in broken preview images.

**To Reproduce**
1. Add an image to public directory
2. Reference the image by the expected URL e.g. `https://app.digivizer.com/platform.jpg`
3. See that it's a redirect to the location rather than returning the image. e.g. `https://app.digivizer.com/_assets/_public/platform.d59298f38.jpg`

**Expected behavior**
I would expect the URL for the image to respond with the image, not redirect.

**Comment by evanderkoogh** [comment]
Hey @qnm, thanks for letting us know about the OpenGraph consumers. That is good to know.
Will have a solution for this once we have released a stable FAB v1, which we should have out in the next week or so.

@geelen, would a workaround be until that time to check in the assets into `public/_assets/platform.d59298f38.jpg` and reference it as `/_assets/platform.d59298f38.jpg` in the html template?

**Comment by geelen** [comment]
Hey @qnm, so this was a long-standing issue with the old FAB implementation, but the good news is, FAB v1, which I've been working on for the last few months, is _extremely_ close to being released. So the best thing would be to upgrade to that.

I'm happy to schedule a time with you to take you through this, but basically what you need to do is this:

* Make a branch off your current `master` or `develop` branch
* Follow the instructions here: https://fab.dev/guides/getting-started, the main parts of which are:
  * Globally install `@fab/cli` (you should see version `v0.0.7-alpha.16`).
  * Run `fab init` in your project. I've spent today making that as resilient as I can to different projects, but there's a chance something might break.
  * That should give you a `fab.config.json5` file and update your `build:fab` scripts in your `package.json`. It's not the smartest tool in the world yet so maybe double check that the things its added are sensible.
  * Running `yarn build:fab` or `npm run build:fab` should generate a `fab.zip` which you can `yarn fab:serve` to fire up locally like normal.
* Pushing this branch up, Linc should build it like any other.

Note: we don't support FAB v1 on Lambda@Edge production, **so please don't merge that branch just yet**. But that's only about 24 hours away—we'll be using it on `app.linc.sh` as of tomorrow.

For today, if you can get your project compiling on FAB v1 and building on Linc and generating preview links then we should be almost certainly good to go. If you have any trouble you can always add me back as contributor for me to debug, or schedule a call for us to diagnose it together.

Thanks!

**Comment by qnm** [comment]
Hi @geelen 

I've installed the fab as requested, it installed ` @fab/cli@0.0.7-alpha.16`.

Here's what I see:

```
qnm@pop-os ~/w/d/frontend> fab init
Error: Cannot find module 'cli-ux'
Require stack:
- /home/qnm/.asdf/installs/nodejs/12.16.1/.npm/lib/node_modules/@fab/cli/lib/helpers/index.js
- /home/qnm/.asdf/installs/nodejs/12.16.1/.npm/lib/node_modules/@fab/cli/lib/errors/BuildFailed.js
- /home/qnm/.asdf/installs/nodejs/12.16.1/.npm/lib/node_modules/@fab/cli/lib/errors/index.js
- /home/qnm/.asdf/installs/nodejs/12.16.1/.npm/lib/node_modules/@fab/cli/lib/actions/Initializer.js
- /home/qnm/.asdf/installs/nodejs/12.16.1/.npm/lib/node_modules/@fab/cli/lib/commands/init.js
- /home/qnm/.asdf/installs/nodejs/12.16.1/.npm/lib/node_modules/@fab/cli/node_modules/@oclif/config/lib/plugin.js
- /home/qnm/.asdf/installs/nodejs/12.16.1/.npm/lib/node_modules/@fab/cli/node_modules/@oclif/config/lib/config.js
- /home/qnm/.asdf/installs/nodejs/12.16.1/.npm/lib/node_modules/@fab/cli/node_modules/@oclif/config/lib/index.js
- /home/qnm/.asdf/installs/nodejs/12.16.1/.npm/lib/node_modules/@fab/cli/node_modules/@oclif/command/lib/command.js
- /home/qnm/.asdf/installs/nodejs/12.16.1/.npm/lib/node_modules/@fab/cli/node_modules/@oclif/command/lib/index.js
- /home/qnm/.asdf/installs/nodejs/12.16.1/.npm/lib/node_modules/@fab/cli/bin/run
    at Object.<anonymous> (~/.asdf/installs/nodejs/12.16.1/.npm/lib/node_modules/@fab/cli/lib/helpers/index.js:12:34)
```

**Comment by geelen** [comment]
Damn, that was my mistake, sorry. I was depending on a dependency of a devDependency, which works on my machine and CI just fine, but... nowhere else.

Pushed `alpha.17` which has this fixed and I've confirmed on a blank machine that it should run, give that a try and let me know if you have troubles?

**Comment by geelen** [comment]
I've also just fixed CI to catch this sort of bug in future too, so sorry for making you the canary in that particular coal mine!

**Comment by qnm** [comment]
Still working through this, just noting this as I go. The `fab init` didn't expect to see `fab` and `fab.zip` in my `.gitignore` and added them again:

```
qnm@pop-os ~/w/d/frontend> cat .gitignore 
.DS_Store
output/
dist/
lib/
tmp/
node_modules/
crash.log
.env
.cache
.*.sw*
.eslintcache
webpack-assets.json
webpack-stats.json
yarn-error.log
npm-debug.log
yarn.lock
styleguide/
.fab
fab.zip
build/
docker-run.sh

/.fab
/fab.zip
```

**Comment by geelen** [comment]
Damn, that happened with buildkite as well. Have pushed some code and a reminder to fix it properly tomorrow, cheers.

**Comment by qnm** [comment]
@geelen Thanks, this seems to be building now.

Does FAB_SETTINGS now work differently? My variable `window.FAB_SETTINGS.REACT_APP_SEGMENT_WRITE_KEY` is now `undefined`.

Did I miss something in the docs?

**Comment by geelen** [comment]
Ah no, _I_ missed something in the docs. `production-settings.json` has been moved to the `production` section of the `settings` section of your `fab.config.json5`. You should be able to copy-paste it straight across:

```json5
// fab.config.json5
{
  // ...
  settings: {
    production: {
      // paste here
    }
  }
}
```

Have added this little prompt to `fab init` for the next people to run into it:

![image](https://user-images.githubusercontent.com/23264/77542778-9ca26d00-6e9e-11ea-91e4-33b1da4f0b2f.png)

Let me know if that fixes it. Still working on the Lambda@Edge releaser for these v1 FABs, will let you know when that's out & you can release this branch.

**Comment by qnm** [comment]
Hey @geelen 

Sorry for the huuuuuuge delay responding here.

This is where I got to:

![image](https://user-images.githubusercontent.com/5343/81931356-4dbabd80-962d-11ea-9a37-d4a366dd16b4.png)

**Comment by geelen** [comment]
Hey @qnm, apologies for the delays at my end as well. That bug looks like a package name that changed in the lead up to the version 1 RC of FABs. The package `@fab/serve-html` is now called `@fab/plugin-render-html`.

Best thing to do would be run `npx --ignore-existing fab init -y` and compare your `git diff` afterwards. It should have renamed your packages in your `fab.config.json5` and added the new dependencies in `package.json`, but might mess with your `build:fab` step so take a look at that to make sure it's right before you commit it.

Apologies about this, realised just before launch that having a `@fab/serve-html` and a `@fab/server` package was a bit too similar!

**Comment by qnm** [comment]
After upgrading to FABv1 I can confirm this works as I would expect. Thanks team!

**Comment by qnm** [comment]
@geelen Sorry, that was premature. I deployed the FABv1 to production and it failed to deploy! The preview URL worked as expected.

**Comment by evanderkoogh** [comment]
That is no good @qnm. @geelen should be looking at this soon.

**Comment by geelen** [comment]
Hey @qnm just been trying to dig into this and figure out what's going wrong.

The bundle `c0b336164` (the one at this URL https://digivizer--c0b336164--production.linc-preview.sh/) looks like it was successfully released to both CF workers and AWS Lambda, but I'm guessing you rolled it back because it failed once it was in production?

Can you confirm that the _deploy_ worked but it was broken once it got there? Or did you see something different?

I have a few options from here, just thought I'd reply to see if I understood what went wrong first.

**Comment by geelen** [comment]
So, options from here, the new Lambda@Edge releaser should be compatible with the old and new FABs just fine, it's just a matter of switching your site to the new config behind the scenes. What that would involve is this:

1. Keep the current `master` as our deploy target (i.e. FAB v0)
2. Bump you to the V2 releaser, which will trigger a redeploy
3. Verify everything worked

4(A). If anything breaks, switch back to the v1 releaser and investigate before retrying (could cause a downtime of ~1 minute, probably less, very unlikely to be any longer)
4(B). If that works, merge your `fab` branch again which should fix your CF worker deploy.

The alternative is slower and safer, but can be done without any behind-the-scenes Linc changes:

1. Set up a non-production AWS Lambda@Edge configuration, duplicating everything about the current CloudFront distrubition etc, but on a test URL.
2. Add those new credentials into the Lambda section of app.linc.sh/sites/digivizer/settings. You'll end up with both V1 releaser (to production) and V2 (to non-prod).

3(A). Confirm new releases are 100% fine on the non-prod URL, then start sending prod traffic to the new CF distribution instead.
3(B). Alternatively, ping me and I'll swap out the non-prod for prod config behind the scenes. If you switch your config in the Linc UI you'll end up with both V1 and V2 releasers trying to send FABs to the same place which would be bad.
4. Merge `fab` branch and deploy the new code.

Let me know what actions you'd like me to take, and when. I'm in GMT+1 so doing something in the middle of your night is relatively easy but the middle of your day is a bit harder, but we can make it work!

**Comment by qnm** [comment]
@geelen Hey! If I’m honest I’m not sure if the deploy was successful. What I saw was Cloudflare trip into offline mode as a 503 was being shown when hitting a URL, which think would be /performance.

I rolled back as the Slack DMs rolled in ;)

For your understanding we use Cloudflare in front of Edge. Not ideal but the reason I would like to move to workers.

**Comment by qnm** [comment]
@geelen Happy for you to try the V2 releaser approach.

**Comment by geelen** [comment]
Ok, have done. Seemed to release without issue. You can now try deploying to CF workers as well.

I would recommend switching your release branch to `fab` at https://app.linc.sh/sites/digivizer/settings, rather than merging/reverting, since it's much faster roll back if anything goes wrong. Once you've confirmed it deployed ok, merge it to master and change the release branch back.

**Comment by qnm** [comment]
Perfect, all done!
