### ISSUE TITLE
Incorrect GH Notification and missing Slack notifications

### ISSUE THREAD

**Issue by qnm** [bitgenics/linc#28]
**Describe the bug**
A recent commit to master failed to deploy, and we were unaware of the issue.

The build failed this way:

![image](https://user-images.githubusercontent.com/5343/81029999-7ecb1d80-8eca-11ea-8404-fe41de907f63.png)

![image](https://user-images.githubusercontent.com/5343/81030013-8c80a300-8eca-11ea-9cbd-d8108e02f640.png)

Additionally, the branch passed checks in GitHub (but NOT in Linc App) which gave false confidence

![image](https://user-images.githubusercontent.com/5343/81030113-f4cf8480-8eca-11ea-9a48-0cb5d2157b16.png)

**To Reproduce**
1. I am unable to reproduce, but can share the build details should you want to look further.

**Expected behavior**
Failures on master should always be reported, regardless of what type of failure.

Failures in the App should also be reflected accurately in GitHub. The absence of a check mark in GH would've given a clue, but the Linc check had passed, so we did not double-check.

**Additional context**
The next commit to master deployed successfully.

**Comment by evanderkoogh** [comment]
Hey @qnm.. that is an interesting edge case.. 

What happened is that the Github errorred when we requested the package.json file, which means that we didn't start the build at all and we set the status to `ignored`

That is all standard behaviour, but I agree that we either should not report the check at all, or we should report a failure, but shouldn't report a pass in any circumstance.

@plexey, could you have a look at exactly how we report `ignored` statuses to Github?

**Comment by plexey** [comment]
Hi @qnm 
You should now receive a report of an `ignored` build status in both GitHub and in Slack.

In GitHub, a build with an `ignored` status will resolve to a failed status check on a commit:
![image](https://user-images.githubusercontent.com/19183324/82404822-9fd46680-9aa5-11ea-916e-13cd814559f0.png)

In Slack, a build with an `ignored` status should resolve to a build failure Slack notification:
![image](https://user-images.githubusercontent.com/19183324/82404946-e9bd4c80-9aa5-11ea-86ca-5bba7e7dc6d4.png)

Please let us know if you run into any other issues :)
