### ISSUE TITLE
Commit was not deployed to production

### ISSUE THREAD

**Issue by qnm** [bitgenics/linc#32]
**Describe the bug**
My latest build did not deploy. It shows as being built, but did not deploy.

![image](https://user-images.githubusercontent.com/5343/85962005-91a52e80-b9f1-11ea-913b-6652c5931291.png)

![image](https://user-images.githubusercontent.com/5343/85962007-9b2e9680-b9f1-11ea-8e6a-618c78263825.png)

**To Reproduce**
Not sure!

**Expected behaviour**
Latest commit should be deployed.

**Comment by evanderkoogh** [comment]
Hey @qnm. During my debugging this particular issue I accidentally released the correct version.

We are currently running a thorough tests through all our deployment logic to try and replicate it and if needed, make it more robust.
