### ISSUE TITLE
Vue 'one click install' !

### ISSUE THREAD

**Issue by ryan-allen** [bitgenics/linc#33]
**Is your feature request related to a problem? Please describe.**
When I npx fab init on a app that was created with vue create it doesn't auto detect.

**Describe the solution you'd like**
Auto configure with Vue's defaults (which is npm run build and output is in /dist/)

**Describe alternatives you've considered**
Taking up a new hobby like whittling.

**Additional context**
Linc is really cool and Glen is smart and handsome.

**Comment by evanderkoogh** [comment]
Hey @ryan-allen, we can all only aspire to be as smart and handsome as Glen.

As this is more a FAB related issue I have copied it over to the FAB repository in [an issue there](https://github.com/fab-spec/fab/issues/200)
