### ISSUE TITLE
Unable to deploy due to "Authentication Error"

### ISSUE THREAD

**Issue by qnm** [bitgenics/linc#35]
**Describe the bug**
Currently unable to deploy due to some Authentication Error.

The following is shown on the main Linc screen:

```
Error releasing to Cloudflare Workers

There was an error releasing bundle 328007299 to Cloudflare Workers. We received the following error:
Fab deploy failed! Error uploading the script, got response: ❤️{"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}❤️

To help diagnose the problem, first confirm that this FAB is working at its preview url: https://digivizer--328007299--production.linc-preview.sh.

If your FAB appears valid, check your Cloudflare Workers Release Config against our guides for Releasing in Linc.

Feel free to get in touch at help@linc.sh or by raising an issue if you're still having trouble.
```
As far as I can tell, the CloudFlare configuration is unchanged from previously successful deploys.

**To Reproduce**
Unsure. This has just started happening.

Linc builds for branches are working correctly.

**Expected behavior**
Deploy to production.

**Comment by evanderkoogh** [comment]
Hey @qnm, I sorry this happened. I just tried to reproduce it and couldn't, and released your site properly. It looks like it was a fluke on Cloudflare's side.

The good news is that we are going to ship a retry release button to the UI *today* in case it happens again in the future.
