### ISSUE TITLE
Cloudflare Workers & Cloudflare DNS Settings - Getting site running on custom domain.

### ISSUE THREAD

**Issue by evolve2k** [bitgenics/linc#36]
**Describe the bug**
I have setup Cloudflare to host my DNS records AND have wired up Cloudflare Workers to deploy & host my site via FAB/Linc.

Previously I've used github pages to host static sites and have setup my DNS records [following github's guides](https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain).

With Linc it seems to imply that once deployed via Cloudflare Workers that I'll be able to access the site on the root domain.
eg https://example.com

After successfully deploying with Linc such that Active Releases shows as 

![Overview](https://user-images.githubusercontent.com/114459/91683361-91f9ab80-eb93-11ea-8ed1-ef1ffd867e17.png)

**Am I missing a step of creating CNAME or A records and pointing them somewhere or does Lincs Cloudflare Workers script handle this for me. Wasn't clear from the documentation, obv I'm missing something.**

**To Reproduce**
For any project I've setup with FAB and deployed to Linc and wired up Cloudflare workers as per the linc instructions I havent been able to get the site to show my deployed code.

I currently get this:
![cant_be_reached](https://user-images.githubusercontent.com/114459/91683912-0ed95500-eb95-11ea-985d-dd4d95898601.png)

**Expected behavior**
My site code run on my custom domain.

**Comment by evanderkoogh** [comment]
Hey @evolve2k, are you hosting your DNS at Cloudflare? Because I just realised that the automatic configuration may only work if you host your DNS there too.

If not let me know and we will figure out what to do. You can only use CNAMEs to point to Cloudflare Workers if you have a Business or Enterprise account though I think?

**Comment by evolve2k** [comment]
>  are you hosting your DNS at Cloudflare?

YES 👍 

> CNAMEs to point to Cloudflare Workers 

I'm not fussy as to using A records or CNAME records. 
Seeking github pages like functionality for supporting a custom domain.
Am attempting to do this all on the Cloudflare Free plan at this stage.

I've done some digging and the community seems to be saying I need to add a dummy A record.
https://community.cloudflare.com/t/setup-workers-on-personal-domain/88012

I'll await your response and then next give that A record a try if you don't have a better idea.

Was wishing that linc might automagically add a record for me ;)

**Comment by evanderkoogh** [comment]
If you are hosting your DNS, I think it should automagically configure your DNS for you, but I would have to defer to @geelen as he is the person who has by far more experience with that than I do. 

You do indeed need a dummy record, so you can absolutely do that manually and it'll work. But I am pretty sure Glen pushed the feature for Linc to do that automatically. And in that case, you should be just fine on the Cloudflare Free plan.

**Comment by geelen** [comment]
Hey @evolve2k, I'm still testing our DNS integration in Linc so it's behind a feature flag for the moment. So you'll need to set up a dummy A record manually (that's what Linc will do in future, btw).

If you use the `.workers.dev` subdomain that Cloudflare gives you that'll be autoconfigured, of course. We're aiming to get the same experience but for Linc sites on custom domains, it's just a bit more complex than we'd like (see: all of DNS, ever).

**Comment by evolve2k** [comment]
All good. Thanks @geelen got that working.

@evanderkoogh quick improvement request.
When a user is new to linc and setting everything up, we're still pretty unsure what linc will do and what it wont.

Regarding this interface:

![Deploy_settings](https://user-images.githubusercontent.com/114459/92195550-7270c480-eeac-11ea-9279-6ab0095728a6.png)

That link "configure DNS records" currently forwards to Cloudflare DNS but provides no guidance as to what I need to do.

Could you folks point it instead to a new linc article that explains how to setup root and www DNS records to work with linc?

(I just set the dummy A record and a 301 page rule for www -> https://example.com/$1 but having those in a linc article would help future users get setup quicker)

Thanks folks!

**Comment by evanderkoogh** [comment]
This is an excellent suggestion @evolve2k. @geelen @plexey, can you make sure this is on a Trello card for release?

**Comment by evolve2k** [comment]
Here's what I added to get everything working.

1. An A record for root pointing to 192.2.0.1 (dummy unused test network)
2. Page rule 301 redirecting www -> root

![DNS_____Account___Cloudflare_-_Web_Performance___Security](https://user-images.githubusercontent.com/114459/92202757-d00e0c80-eebe-11ea-9594-9c2391b3b46c.png)

![Page_Rules____Account___Cloudflare_-_Web_Performance___Security](https://user-images.githubusercontent.com/114459/92202590-81607280-eebe-11ea-9da6-fe4fe66c6419.png)
