### ISSUE TITLE
Changed my release branch and permanetly broke the Fab deployment to CW

### ISSUE THREAD

**Issue by evolve2k** [bitgenics/linc#37]
**Describe the bug**
We chose to change our primary branch from 'master' to 'main' and in the process seem to have permanently broken FAB deployment to CW.

**To Reproduce**
1. Went Settings > Deploy within the linc project
2. Changed release branch from 'master' to 'main' both of which are valid branches in the github repo.
3. On the Linc Overview page, the Active Release deployment satus is now Failed to Deploy with this error:

    Fab deploy failed! Error uploading the script, got response: ❤️{"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}❤️

**Screenshots**

![Overview](https://user-images.githubusercontent.com/114459/91687365-aee7ac00-eb9e-11ea-9c88-dfeaf3e63f7b.png)

**Additional context**

Even thought the Active Release is failing, the linc build related to the underlying commit is passing, see screenshot above.

_This is the same project as https://github.com/bitgenics/linc/issues/36, separating as I imagine it's a separate issue. Wishing now I'd just left it as master while I let you resolve #36_

**Comment by evanderkoogh** [comment]
Hey @evolve2k, this has been a recurring issue with Cloudflare that we have seen over the past few weeks. It usually goes away in an hour or so. Can you retry the deploy?

**Comment by plexey** [comment]
Hi @evolve2k ,

As @evanderkoogh mentioned, you can retry a deploy through the Linc interface:
![image](https://user-images.githubusercontent.com/19183324/91796654-16b3fa80-ec64-11ea-909f-ce7eb4bedb14.png)

Clicking this button will trigger a re-release which, among other things, can be handy if your deployments fail due to transient network issues.

We've triggered a re-release for your Linc site which resulted in a successful release to Cloudflare Workers.

**Comment by evanderkoogh** [comment]
So changing the branch wasn't what broke it, that just triggered a re-release that ran into an issue with Cloudflare that was fixed with a retry a while later.

**Comment by evolve2k** [comment]
Oh thanks again for looking. I seem to be good at bumping into all the things 😂
Yes can confirm on my end 'Deployment Status' once again has the green tick.

**Comment by evanderkoogh** [comment]
Haha.. This is the one that is actually outside of our control for a change! :D
