### ISSUE TITLE
Platform connection issues should have email/slack alerts, too

### ISSUE THREAD

**Issue by qnm** [bitgenics/linc#39]
**Is your feature request related to a problem? Please describe.**
I logged into Linc to see the following alert. 

![image](https://user-images.githubusercontent.com/5343/98182718-8db68980-1f5a-11eb-8334-a20e18958196.png)

**Describe the solution you'd like**
It would be much more useful if that alert came to me, using email or slack or something!

**Describe alternatives you've considered**
I could... log in daily to see if something's broken, or wait for my team to complain? :shrugs:

**Comment by evanderkoogh** [comment]
You are absolutely right @qnm. We will get on that as a matter of priority. We are currently wrapping up a public launch for next week, but after that it will be top of our list. We will reach out when we have something.
