### ISSUE TITLE
Is this the end? Linc Preview Workers are not responding.

### ISSUE THREAD

**Issue by qnm** [bitgenics/linc#45]
**Describe the bug**
A PR will deploy to a `linc` preview URL.

This has worked until today. Here's what I see:

![image](https://user-images.githubusercontent.com/5343/169450063-d113365f-4a26-4f95-8acb-99ce8bed0471.png)

Cloudflare Pages isn't quite as complete as Linc is/was - particular around multiple environments. The Preview / Production distinction that Pages has isn't as flexible as Environment links for each PR.

I'm assuming the worst, but please let me know what's happening - if anything!

**Comment by evanderkoogh** [comment]
Hey @qnm.. While there are indeed plans to phase out Linc over the next few weeks/months, it is certainly not our intention to stop so suddenly and without any warning.

We did do a whole bunch of transfers of our domains from the Linc AWS account to the Cloudflare account and something might have gone wrong there. I am going to figure that out.. and then lets chat later in the week about the near future :)
