### ISSUE TITLE
Linc having trouble accessing package.json

### ISSUE THREAD

**Issue by jxom** [bitgenics/linc#9]
**Describe the bug**
Hey!

Linc is having a bit of trouble locating the package.json for [Fannypack](https://github.com/fannypackui/fannypack). 

In the build log I am getting: 

```
Error accessing /package.json. Does that file exist in this commit?
```

It does exist - so I'm not too sure why I'm getting this kind of error!

This seemed to be working a few commits ago, so not too sure why it's not working all of a sudden.

**Screenshots**
<img width="678" alt="Screen Shot 2019-04-24 at 5 06 57 pm" src="https://user-images.githubusercontent.com/7336481/56639285-a8e0e180-66b3-11e9-9311-352a42d5a01e.png">

**Comment by evanderkoogh** [comment]
Hey @jxom. That shouldn't be happening at all. I will investigate :)

**Comment by evanderkoogh** [comment]
@jxom The mystery deepens. I have located the problem. The webhook we get from Github includes a commit_sha that is not the commit-sha of the head_commit for all your recent commits.

Now I have no clue how that could possibly be the case. Did you make any change in git/Github around the time it went wrong?
Tomorrow I will roll out a fix that will instead look at the head commit for the commit-sha and rerun all of your current builds. That should take care of the problem.

**Comment by jxom** [comment]
Nope, didn't change anything with GitHub :\

Thanks!
